export const RESOURCE_FETCH_REQUESTED = "RESOURCE_FETCH_REQUESTED";
export type RESOURCE_FETCH_REQUESTED = typeof RESOURCE_FETCH_REQUESTED;

export const RESOURCE_FETCH_SUCCEEDED = "RESOURCE_FETCH_SUCCEEDED";
export type RESOURCE_FETCH_SUCCEEDED = typeof RESOURCE_FETCH_SUCCEEDED;

export const RESOURCE_FETCH_FAILED = "RESOURCE_FETCH_FAILED";
export type RESOURCE_FETCH_FAILED = typeof RESOURCE_FETCH_FAILED;
